### ISSUE TITLE
No longer finding new downloads

### ISSUE THREAD

**Issue by willvincent** [carlosflorencio/laracasts-downloader#100]
Not sure when it changed, but new downloads are no longer being found, for at least the past two weeks.  I have at least half a dozen not downloaded, and it simply tells me there are no new lessons or episodes on run, regardless of any flags passed, etc.

> 0 new lessons and 0 episodes. 1.142s elapsed with 6.00Mb of memory usage.

**Comment by zildjianjax** [comment]
same goes for me.

**Comment by carlosflorencio** [comment]
Is any contributor available to tackle this?

**Comment by willvincent** [comment]
Looks like the issue is that the algolia query result does not have updated episode counts for series.  For example, the laravel 6 from scratch series has 39 episodes as of right now, and the result from Algolia meanwhile shows 37:

```
Array (
                    [slug] => laravel-6-from-scratch
                    [episode_count] => 37
                    [path] => /series/laravel-6-from-scratch
                    [type] => series
```

**Comment by kossa** [comment]
Me too I tried to download https://laracasts.com/series/code-katas-with-phpunit with : 

`php start.php -s "code-katas-with-phpunit"`

I got : 

```
> Successfull!

====================================
Starting Collecting the data
====================================

====================================
Checking for options {"s":"code-katas-with-phpunit"}
====================================
> Series names provided: ["code-katas-with-phpunit"]
> Series names provided: ["code-katas-with-phpunit"]

====================================
Checking if series and lessons exists
====================================
> Series 'code-katas-with-phpunit' not found!

====================================
Downloading
====================================
> 0 new lessons and 0 episodes. 7.792s elapsed with 8.00Mb of memory usage.
```

**Comment by iforwms** [comment]
Also having the same issue. Is there a way to bust the Algolia cache?

**Comment by matinwd** [comment]
Any way found?

**Comment by inDeev** [comment]
Same here, will be any update?

**Comment by ertuzio** [comment]
Bump...
Still not working!

**Comment by carlosflorencio** [comment]
Can someone test https://github.com/carlosflorencio/laracasts-downloader/pull/98 and check the comments?

**Comment by willvincent** [comment]
This isn't a rate-limit issue. The result set from algolia simply fails to include newer data.

May not be solvable.

**Comment by inDeev** [comment]
Fortunately, for now it means to manually download ~15 lessons, just compare latest lesson, you have and newer download manually. https://laracasts.com/whats-new

**Comment by carlosflorencio** [comment]
Can someone test this PR https://github.com/carlosflorencio/laracasts-downloader/pull/102 ?

**Comment by carlosflorencio** [comment]
Issue seems solved, thanks @AmirRezaM75 for the fix.

**Comment by kossa** [comment]
Alright, works fine, thank you @AmirRezaM75
