### ISSUE TITLE
not downloading latest videos

### ISSUE THREAD

**Issue by vesper8** [carlosflorencio/laracasts-downloader#103]
For example, the "whatcha-working-on" series

A new video was just uploaded in the last 24 hours:

https://laracasts.com/series/whatcha-working-on/episodes/39

I have all previous 38 but when I run the downloader it doesn't find the new one (# 39) and says no available downloads

**Comment by vesper8** [comment]
I'm also seeing a warning `Series 'programming-terms-explained' not found!` but the series does exist: https://laracasts.com/series/programming-terms-explained

**Comment by carlosflorencio** [comment]
Algolia indexing delay?

**Comment by vesper8** [comment]
just tried again now, it's been 48 hours now and it's still not downloading the new video

**Comment by silentangelph** [comment]
Same as here. I'm getting a 404 not found error.

> Download started: 40 - What I Learned About Cypress on Day 2 . . . . Saving on series/whatcha-working-on folder.
> ERROR: Client error response [url] https://player.vimeo.com/external/391567107.m3u8?s=f30fcb1f66ec8eeabc4322e972a5ab0eb6e54d39&download=1 [status code] 404 [reason phrase] Not Found

**Comment by kossa** [comment]
Me too 
![image](https://user-images.githubusercontent.com/1175584/74600445-330a9400-5092-11ea-8981-fc77f01e26ea.png)

**Comment by AmirRezaM75** [comment]
I visit this page [watcha-working-on](https://laracasts.com/series/whatcha-working-on/episodes/40) and I couldn't click on download button and download it manually and it responses with this message:
 "Sorry, This video does not exist.". 
So I think Jeffry should fix it not us.

And about "programming-terms-explained" series. It's not indexed in Algolia neither in laracasts series page so we can't find it. 
we should wait for it or create a new option to crawl that.

**Comment by willvincent** [comment]
Ideally though, if there are other videos, it ought to continue after a 404, not completely bail on the whole process.

**Comment by AmirRezaM75** [comment]
@willvincent Yea, you are right
