### ISSUE TITLE
Too Many Request

### ISSUE THREAD

**Issue by Mohib1992** [carlosflorencio/laracasts-downloader#107]
I start downloading a series but in the middle i find this bug and then its stop to download.

> Client error response [url] https://laracasts.com/downloads/eyJpdiI6ImRZUHl2L3
owQjBSRElNRnRDMXdnbmc9PSIsInZhbHVlIjoidktrdEVFTEFGL1hadndLT1lkUmxMZz09IiwibWFjIj
oiMDg4MTMwMTg0YTMxMzliZGRhMmM3ZDEwYTMxOTBkYWI2MGUxNjBjZGJmZjc0MDdkZDczNDVhN2E0OG
ZmM2I2MCJ9 [status code] 429 [reason phrase] Too Many Requests
> Current: 1 of 5 total. Left: 4

**Comment by agarzon** [comment]
That is normal, you are limited to 30 downloads per day. This is mentioned in the README.md file
