### ISSUE TITLE
Video - 'What I Learned About Cypress on Day 2' can't be downloaded

### ISSUE THREAD

**Issue by ertuzio** [carlosflorencio/laracasts-downloader#108]
It's probably some error from the vimeo side but I just wanted to share that this video can't be downloaded.

https://laracasts.com/series/whatcha-working-on/episodes/40

even when you try to download that video from the laracasts site directly it says:
Sorry
This video does not exist.

But you can watch it on Laracasts if you start it.

**Comment by agarzon** [comment]
Funny, I got stuck in the exact same video and yes, the video is there but "undownloadable" .

I guess a workaround is to download that video manually with a browser extension (for example) and name it correctly in yor Downloads folder so the script can move fordward.

**Comment by agarzon** [comment]
Hi again, just to report my workaround worked well.

The file name must be named as "**40-What I Learned About Cypress on Day 2.mp4**", and you can get it easily with this chrome extension https://chrome.google.com/webstore/detail/simple-vimeo-downloader/mffmjlddchdccijipncbjhoabgmphjfb?hl=en

**Comment by AmirRezaM75** [comment]
I close this issue because it's old and fixed in newer version
