### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by toyjack** [carlosflorencio/laracasts-downloader#11]
Hello, guys.
It just comes up errors like this:

```
laracasts-downloader git:(master) ✗ php start.php

====================================
Starting Collecting the data
====================================
ERROR: Server error response [url] https://laracasts.com/lessons/?page=6 [status code] 500 [reason phrase] Internal Server Error%

```

And the error page changes. Could anybody tell why?

Thank you very much!

**Comment by carlosflorencio** [comment]
Hi,

Maybe the website was down at that time?
Can you try again?

**Comment by toyjack** [comment]
Thanks for your reply.

It happened while I was watching the video, so I think the website should be online at that time.

And I just tried last minute, it turned out like this:

```
====================================
Starting Collecting the data
====================================
ERROR: Server error response [url] https://laracasts.com/lessons/?page=3 [status code] 504 [reason phrase] Gateway Time-out%
```

And since I'm living abroad of US, is there any possible because of my local gateway?
If it's a local network error, I think I can only download videos by manually.(sad TT)

**Comment by carlosflorencio** [comment]
Can you open that link in your browser and see if it works?

**Comment by toyjack** [comment]
I get the same error in my browser when I just runnde the start.php. 
But if I wait for few minutes after the start.php and access the page again, errors gone away.

**Comment by carlosflorencio** [comment]
Very strange.
Sorry mate, can't help you :disappointed:

**Comment by toyjack** [comment]
😄Thanks anyway. Maybe it's my network's problem.
