### ISSUE TITLE
Not working, again

### ISSUE THREAD

**Issue by willvincent** [carlosflorencio/laracasts-downloader#112]
The structure of the series page has changed again, so new content once again fails to be found and downloaded.

I think long term another solution is going to be necessary because the series page no longer lists _all_ series, instead it has a couple featured recently updated items, and a few other groupings of things, but it's pretty dramatically different than it was. 

Have a PR that will get it working for the things that _do_ remain linked on that page, and if run on a regular basis to keep newly added items pulled in it may be sufficient, but won't work for anyone who doesn't _already_ have the majority of the library downloaded to get older things not listed there.

May be near the end of the line on this repo's usefulness without a major rewrite.

**Comment by carlosflorencio** [comment]
Thanks for raising this and submitting a workaround.

I don't work anymore with PHP so I'll happily accept suggestions (via PR) that circumvent this new limitation on the website.
