### ISSUE TITLE
Cannot download "blade-component-cookbook" series

### ISSUE THREAD

**Issue by kossa** [carlosflorencio/laracasts-downloader#114]
When I run : `php start.php -s "blade-component-cookbook"` I got only 2 episodes, but if you check on laracast you'll see 9 episodes => https://laracasts.com/series/blade-component-cookbook

Even if you remove the folder and you try again

![image](https://user-images.githubusercontent.com/1175584/86463701-e87a7300-bd25-11ea-82ae-49203023f601.png)

![image](https://user-images.githubusercontent.com/1175584/86463857-355e4980-bd26-11ea-8f65-9faeef003463.png)

**Comment by AmirRezaM75** [comment]
I close this issue because it's old and fixed in newer version
