### ISSUE TITLE
excluding serieses and lessons

### ISSUE THREAD

**Issue by lorvent** [carlosflorencio/laracasts-downloader#115]
Hello,
i might download all videos but some are too old that i don't want to see them at all.

so is there is any exclude option is there?

earlier i was using another downloader which has such option.

or do you have any plans to implement it?

----

or ability to add multiple seriese slugs in single command is also great!

thanks

**Comment by carlosflorencio** [comment]
Hi,

I don't have any plans to implement it, but I'll accept PRs.

Regards
