### ISSUE TITLE
is it possible to download multiple series videos at a time?

### ISSUE THREAD

**Issue by lorvent** [carlosflorencio/laracasts-downloader#117]
Hello,

is it possible to download multiple series at a time?

for a example, if i run something like this `php start.php -s  "whats-new-in-vue-3" "learn-vue-2-step-by-step" "lets-build-a-forum-with-laravel" "object-oriented-principles-in-php" "laravel-6-from-scratch"`

it does nothing, eventhough i didn't download any video of `laravel-6-from-scratch` series

thanks.

**Comment by AmirRezaM75** [comment]
I think you should use ``-s`` option before each series
``php start.php -s "whats-new-in-vue-3" -s "learn-vue-2-step-by-step" -s "lets-build-a-forum-with-laravel"``
