### ISSUE TITLE
Metadata 

### ISSUE THREAD

**Issue by jpscharf** [carlosflorencio/laracasts-downloader#12]
Would it be possible to download the lesson metadata, i.e. synopsis, etc... and embed it into the video file?

**Comment by carlosflorencio** [comment]
Hi, maybe its possible but i will not add it. Sorry. 

I accept pull requests.

**Comment by insign** [comment]
@iamfreee Can you specify the part of the script you can get the page source code to let something of the community make it happen easily?

**Comment by carlosflorencio** [comment]
Hi, 

https://github.com/iamfreee/laracasts-downloader/blob/master/App/Http/Resolver.php#L150

This class has two methods to download the page of a serie episode and a lesson,
downloadSerieEpisode() & downloadLesson(), inside: $html = $this->getPage($path);
