### ISSUE TITLE
Getting errors Too Many Requests

### ISSUE THREAD

**Issue by ramseylourens** [carlosflorencio/laracasts-downloader#121]
This is one of the errors after running PHP start.php
```
 Download started: 03 - The Composition API . . . . Saving on series/whats-new-in-vue-3 folder.
> Client error response [url] https://laracasts.com/downloads/eyJpdiI6ImFyb2poZkVac203c0J2TWl3NUF4elE9PSIsInZhbHVlIjoiU05LWmxrRnBJeVpvOEtpcy9kY2xIUT09IiwibWFjIjoiMTRhNWJmM2UzYjAwYjExODI5YTU1NmY4MGZkYWFmOWQ2NTY5MTRmNmZiMDMwYmI0ZDMzZTg5MzE2NzAzZTU0ZiJ9 [status code] 429 [reason phrase] Too Many Requests
> Current: 87 of 1293 total. Left: 1206
```

Should I wait or is this as a response to this downloading script, basically stopping you from downloading the movies?

**Comment by carlosflorencio** [comment]
It's a protection mechanism, you need to wait some time (don't have more details).

**Comment by blaqmajik** [comment]
There is a way to work around this: instead of downloading from the link that Laracasts offers, download the file from the same location the Vimeo player is using.

This fork was changed accordingly: https://github.com/blaqmajik/laracasts-downloader

**Comment by carlosflorencio** [comment]
Hey @blaqmajik do you want to make a PR?

**Comment by blaqmajik** [comment]
> Hey @blaqmajik do you want to make a PR?

I'll need to see if I find the time in the next days.

Do you think this should be optional via a command line option or should I just replace the entire current way of downloading?

**Comment by carlosflorencio** [comment]
Not sure if its possible but I'd suggest the following download logic:
1. Try download via laracasts download link first
2. Download via vimeo (if the above fails)

This wouldn't require any aditional parameters right?

**Comment by blaqmajik** [comment]
That sounds good and yes, no additional parameters needed in that case.

**Comment by ghost** [comment]
Is this fix finding a way to this repository?

**Comment by blaqmajik** [comment]
I am sorry, I probably won't find the time to work on a PR (e.g. clean things up and make them more bulletproof as opposed to the hack I've made so far) before my subscription expires and I don't plan on extending it currently.

But the code is available in my fork for everyone to take...

**Comment by AmirRezaM75** [comment]
Currently there is no way to download more than 30 videos per day using Laracasts download link. with [new release](https://github.com/carlosflorencio/laracasts-downloader/pull/140) we use ``DOWNLOAD_SOURCE=vimeo`` to cope with it.
