### ISSUE TITLE
Cannot Call the CURLOPT_PROGRESSFUNCTION

### ISSUE THREAD

**Issue by skino2019** [carlosflorencio/laracasts-downloader#127]
Im getting a weird error when i run the php start.php. it seems to grab all the information about the series on Laracasts but as soon as it tries to download i get spammed with the below error.

PHP Warning:  curl_exec(): Cannot call the CURLOPT_PROGRESSFUNCTION in /home/skino/www/laracasts-downloader/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php on line 89

I thought it might be a cert error so i downloaded and installed the cacert.pem and pointed to it in my .ini

Im running Pop!_OS, with Laravel Linux Valet using PHP 8.1

any suggestions would be hugely appreciated.

**Comment by MohdSohail** [comment]
Use PHP >= 7.2 but PHP < 8. It will work.

**Comment by AmirRezaM75** [comment]
Related to https://github.com/carlosflorencio/laracasts-downloader/issues/119
