### ISSUE TITLE
cant download a series or a single episode of a series  

### ISSUE THREAD

**Issue by M-hanif** [carlosflorencio/laracasts-downloader#128]
i have php7.4 in my ubuntu machine and i have installed and configured this package. everything looks fine and without any error 
when i search for a series like 
php start.php -s "laravel-8-from-scratch" -e "1";
the process of searching the series start and i can see the exact series name in laravel section of the searchs in my terminal and at the end i get 
Checking for options {"s":"laravel-8-from-scratch","e":"1"}

====================================
> Series names provided: ["laravel-8-from-scratch"]
> Series names provided: ["laravel-8-from-scratch"]
> Episode numbers provided: "1"
> Episode numbers provided: ["1"]
====================================
Checking if series exists
====================================
> Series "laravel-8-from-scratch" found!

====================================
Downloading
====================================
> 0 new episodes. 84.952s elapsed with 6.00Mb of memory usage.

> Finished! Downloaded 0 new episodes. Failed: 0
it looks that the app is not able to download. it can find the series but not downloading it.

please help me if something is messing in my scenario

**Comment by FSElias** [comment]
It seems that the "download" key is no longer in the encoded JSON string

**Comment by M-hanif** [comment]
@carlosflorencio 
do you have any idea?

**Comment by carlosflorencio** [comment]
Sorry @M-hanif, I no longer use this tool and I don't have the time atm to look into this.

**Comment by AmirRezaM75** [comment]
> It seems that the "download" key is no longer in the encoded JSON string

That's right
probably will find a solution for new structure in next week. (can't promise :sweat_smile:)

**Comment by AmirRezaM75** [comment]
I fixed that and can get download link.
**But there is one big important issue**
It downloads the best quality (2K resoluation :flushed: ), thus a 4 minute video occupy 400 MB of your disk and really not worth it
Is there anyone here to help me on that?

this is redirection steps to get download link

``https://laracasts.com/downloads/<hash>``

``https://player.vimeo.com/progressive_redirect/download/644886096/container/<uuid>/1b7caecf/2-five-quick-tips-for-using-vscode-for-php-development%20%28Original%29.mp4?expires=1646726775&loc=external&oauth2_token_id=<token>&signature=<hash>``

``https://vod-progressive.akamaized.net/exp=1646892602~acl=%2Fvimeo-prod-src-reg-us-east1%2Fvideos%2F2957616931~hmac=<hash>/vimeo-prod-src-reg-us-east1/videos/2957616931?download=1&filename=2-five-quick-tips-for-using-vscode-for-php-development+%28Original%29.mp4&source=1``

**Comment by mouson** [comment]
@AmirRezaM75  thanks.

you can try add parameter `quality=1080p`, more information: 
https://vimeo.zendesk.com/hc/en-us/articles/224983008-Set-a-default-quality-for-embedded-videos

**Comment by FSElias** [comment]
Thank you very much @AmirRezaM75,
About @mouson 's suggestion, can there be a .env value like video_download_quality=1080p or something like that?

**Comment by AmirRezaM75** [comment]
@mouson thanks for your reply, I tried that but didn't work. :(
I think these parameters only work for embedded videos (as article's title says that)

I pushed changes in ``develop`` branch.
If you want; you can give it a shot

@FSElias yeah we should set it in .env

**Comment by AmirRezaM75** [comment]
@mouson @FSElias
I fixed that :smiley:
Please check it out and test it and send your feedback in related pull request before merging to master.

**Comment by BennySama** [comment]
I do get an error while downloading videos

> Download started: 02 - Let and Const . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 41 of 49 total. Left: 8

> Download started: 03 - Arrow Functions Point the Way . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 42 of 49 total. Left: 7

> Download started: 04 - Class is in Session . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 43 of 49 total. Left: 6

> Download started: 05 - Promises are Made . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 44 of 49 total. Left: 5

> Download started: 06 - Async and Await . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 45 of 49 total. Left: 4

> Download started: 07 - Maps and Sets are Special Objects . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 46 of 49 total. Left: 3

> Download started: 08 - Declarative Methods . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 47 of 49 total. Left: 2

> Download started: 09 - Demystifying Modules . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 48 of 49 total. Left: 1

> Download started: 10 - Wrapping It All Up . . . . Saving on series/modern-javascript-basics

Notice: Undefined index: vimeo_id in F:\laracasts\App\Http\Resolver.php on line 139
> Client error response [url] https://player.vimeo.com/video/ [status code] 404 [reason phrase] Not Found
> Current: 49 of 49 total. Left: 0

**Comment by AmirRezaM75** [comment]
@BennySama wierd :/ ,i download  whole series today.
Once I saw this error when i wasn't logged in, im pretty sure i throw exception when u are not logged in or an active subscription.
Are you working on master branch?

**Comment by AmirRezaM75** [comment]
@BennySama delete your cache.php in Downloads folder

**Comment by BennySama** [comment]
> @BennySama delete your cache.php in Downloads folder

Seems to work now, I already started to write a reply that I try to redownload everything. Seems like deleting the old cache.php fixed it. Thank you!
