### ISSUE TITLE
failed to open stream: Permission denied

### ISSUE THREAD

**Issue by HelKyle** [carlosflorencio/laracasts-downloader#13]
Out of date ?

**Comment by carlosflorencio** [comment]
I don't have a subscription active, so i cant test. sorry

**Comment by carlosflorencio** [comment]
Closing, working good at the moment.

**Comment by beyera** [comment]
Having Same Problem, Tried on 2 different versions ubuntu server:

# 

# Starting Collecting the data

> 216 new lessons and 496 episodes. 5.841s elapsed with 3.25Mb of memory usage.

# 

# Authenticating

> Successfull!

# 

# Downloading Lessons

> Download started: prevent-spam-with-recaptcha . . . . Saving on lessons folder.
> ERROR: Unable to open ./lessons/0216-prevent-spam-with-recaptcha.mp4 using mode r+: fopen(./lessons/0216-prevent-spam-with-recaptcha.mp4): failed to open stream: No such file or directory

**Comment by beyera** [comment]
@HelKyle check if php5-curl extension is installed.
