### ISSUE TITLE
download with out credentials removed . why? 

### ISSUE THREAD

**Issue by hoseininjast** [carlosflorencio/laracasts-downloader#131]
hi
in previous version we can start script without entering any email | password but in new update we must provide credentials , why we cant download free courses and lessons ?
suggestion : can download a video from playing section ? or dump showing video and after finishing create full video?

**Comment by madurapa** [comment]
You can comment on line 160 to bypass the no active subscription error in /App/Downloader.php

**Comment by AmirRezaM75** [comment]
No longer need to have active subscription.

But maybe bring it back if causes problem with cache
