### ISSUE TITLE
Retry download after connection fail! PHP Warning:  curl_exec(): Cannot call the CURLOPT_PROGRESSFUNCTION in H:\laraca sts-downloader\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php on line 89

### ISSUE THREAD

**Issue by morshedAlamAD** [carlosflorencio/laracasts-downloader#132]
Does anyone else have the issue..??

**Comment by mouson** [comment]
What is your PHP version?

**Comment by morshedAlamAD** [comment]
php 8.1.4

**Comment by mouson** [comment]
@morshedAlamAD  #127 

> Use PHP >= 7.2 but PHP < 8. It will work.

**Comment by morshedAlamAD** [comment]
hmm I see let me try.

**Comment by jpmurray** [comment]
Can confirm, on PHP 7.4, it works perfectly !

**Comment by Aybee5** [comment]
I am new to PHP ecosystem

I have PHP 8 install and later installed v7.4

`brew install php@7.4`

How do I switch to v7.4 and use it for this?

**Comment by jpmurray** [comment]
> How do I switch to v7.4 and use it for this?

Check [this article](https://dev.to/dcblog/switching-between-php-versions-with-homebrew-991) for the commands, and a small bash script to make it easier ! :)

**Comment by Aybee5** [comment]
Thank you very much for this, it works

**Comment by AmirRezaM75** [comment]
Related to https://github.com/carlosflorencio/laracasts-downloader/issues/119
