### ISSUE TITLE
Auth fail, no csrf token

### ISSUE THREAD

**Issue by willvincent** [carlosflorencio/laracasts-downloader#136]
I like the new approach for downloading, but am unable to use it as I get errors while it's attempting to fetch the csrf token in order to login. It looks like it's trying to find it in the dom, but it doesn't exist in the dom.

> ====================================
Authenticating
====================================
PHP Warning:  Undefined array key 1 in App/Html/Parser.php on line 127
PHP Warning:  Trying to access array offset on value of type null in App/Downloader.php on line 150
ERROR: You don't have active subscription!

I have a forever account, so don't really _need_ to be able to automate downloads, or do any downloading at all of course, but I like having my local library, so would be cool if I could use this again. 

Don't have time to dig into this to try to correct it myself.

**Comment by AmirRezaM75** [comment]
Yeah I'm gonna examine it at weekend
