### ISSUE TITLE
Two seperate files for video and audio are getting download 

### ISSUE THREAD

**Issue by shanks25** [carlosflorencio/laracasts-downloader#144]
Hi, whenever I am running php start.php -s " series-slug-example" for e.g  **php start.php -s " three-minute-tips** two separate files are getting downloaded in the project root directory for video and the audio. file extensions are **m4a** and **m4v**.  also file names are not episode names - 1b8433e1-4177-4005-b130-25381e399ba6.m4a

I am using PHP 7.4.30

.env
```
EMAIL=kunal.rajput2511@gmail.com
PASSWORD=my-password
LOCAL_PATH=Downloads
LESSONS_FOLDER=lessons
SERIES_FOLDER=series
TIMEZONE=Europe/London
RETRY_DOWNLOAD=false
VIDEO_QUALITY=1080p
DOWNLOAD_SOURCE=vimeo
```

**Comment by AmirRezaM75** [comment]
That's intentional, the two files (video and audio) downloaded first then combine together using ffmpeg then will be deleted.

**Comment by shanks25** [comment]
Sorry I missed mentioning, I am getting "_**_Finished! Downloaded 0 new episodes. Failed: 1_**_" in the terminal. Also, the two files are not getting deleted.

here is the screenshot link https://i.imgur.com/ifCANdX.jpg

**Comment by AmirRezaM75** [comment]
Probably ffmpeg have not been installed on your machine. execute ``ffmpeg --help`` in terminal and check the output.
For me It's working on ffmpeg version 4.2.7
also you can set ``DOWNLOAD_SOURCE=laracasts`` if you don't want to use ffmpeg.
also composer.lock has been changed and need to run ``composer install``
you can safely remove those 2 files.

**Comment by shanks25** [comment]
In the .env.example the download source was `vimeo,` changing the download source to laracasts in the .env file solved the problem. `DOWNLOAD_SOURCE=laracasts` .

Also for Vimeo I had to install ffmpeg

Thank you
