### ISSUE TITLE
Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by PNP-MA** [carlosflorencio/laracasts-downloader#146]
Download started: 02 - Dialog . . . . Saving on series/learn-headless-ui

Notice: Undefined offset: 1 in /Users/mac/Downloads/laracasts-downloader/App/Vimeo/VimeoRepository.php on line 36

Notice: Trying to access array offset on value of type null in /Users/mac/Downloads/laracasts-downloader/App/Vimeo/VimeoRepository.php on line 36

**Comment by AmirRezaM75** [comment]
I have just test it. there is no problem. make sure to use latest version of the script by ``git pull``
