### ISSUE TITLE
Fail to merge sources when DOWNLOAD_SOURCE is vimeo in Windows wsl2 docker

### ISSUE THREAD

**Issue by kwarnkham** [carlosflorencio/laracasts-downloader#147]
The downloader failed to merge source when DOWNLOAD_SOURCE is vimeo in Windows wsl2 docker.

It seems to be Permission error tho I'm not sure.

The error code is 127.

**Comment by AmirRezaM75** [comment]
Please provide more details about error.
I think FFmpeg is not installed in docker.

**Comment by AmirRezaM75** [comment]
I tried to fix the issue. Can you test it on ``develop`` branch?

**Comment by maghogrebban** [comment]
@AmirRezaM75 I can confirm `develop` fixed the issue

**Comment by maghogrebban** [comment]
@AmirRezaM75 I can confirm `develop` branch fixed the issue

**Comment by mattiasghodsian** [comment]
@AmirRezaM75 I can confirm develop branch fixed the issue

**Comment by paulpreibisch** [comment]
hi there, i tried this downloader, however, it seams to save each file as two separate files m4v and m4a, and does not save in a separate folder - instead, all files are saved in the root folder, and given a uuid as a name - making it impossible to know which video is which.  I have opened an issue for this. Can you please check?

**Comment by ivancronicsco** [comment]
> I tried to fix the issue. Can you test it on `develop` branch?

this fix is work for me, thanks!!!

**Comment by AmirRezaM75** [comment]
> hi there, i tried this downloader, however, it seams to save each file as two separate files m4v and m4a, and does not save in a separate folder - instead, all files are saved in the root folder, and given a uuid as a name - making it impossible to know which video is which. I have opened an issue for this. Can you please check?

@paulpreibisch This is intended behavior. We download audio file and video file separately and merge them using FFmpeg, then move it to appropriate folder and correct filename
