### ISSUE TITLE
Deprecated: Return type of  *

### ISSUE THREAD

**Issue by PNP-MA** [carlosflorencio/laracasts-downloader#150]
PHP 8.1.16 (cli) (built: Feb 23 2023 12:59:08) (NTS)

Deprecated: Return type of GuzzleHttp\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mac/Movies/laracasts-downloader/vendor/guzzlehttp/guzzle/src/HasDataTrait.php on line 43

Deprecated: Return type of GuzzleHttp\Ring\Future\CompletedFutureArray::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mac/Movies/laracasts-downloader/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureArray.php on line 14

Deprecated: Return type of GuzzleHttp\Ring\Future\CompletedFutureArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mac/Movies/laracasts-downloader/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureArray.php on line 19

Deprecated: Return type of GuzzleHttp\Ring\Future\CompletedFutureArray::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mac/Movies/laracasts-downloader/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureArray.php on line 24

Deprecated: Return type of GuzzleHttp\Ring\Future\CompletedFutureArray::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mac/Movies/laracasts-downloader/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureArray.php on line 29

Deprecated: Return type of GuzzleHttp\Ring\Future\CompletedFutureArray::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mac/Movies/laracasts-downloader/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureArray.php on line 34

Deprecated: Return type of GuzzleHttp\Ring\Future\CompletedFutureArray::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mac/Movies/laracasts-downloader/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureArray.php on line 39

**Comment by AmirRezaM75** [comment]
It's not compatible with PHP 8

https://github.com/carlosflorencio/laracasts-downloader/issues/127
