### ISSUE TITLE
Videos do not download into separate folders, and also download mp4 and m4a and m4v

### ISSUE THREAD

**Issue by paulpreibisch** [carlosflorencio/laracasts-downloader#151]
Hi there, 

I set up my env so that videos would download into:

```
EMAIL=myemail
PASSWORD=mypassword
LOCAL_PATH=Videos/Laracasts
LESSONS_FOLDER=lessons
SERIES_FOLDER=series
TIMEZONE=Europe/London
RETRY_DOWNLOAD=false
VIDEO_QUALITY=1080p
DOWNLOAD_SOURCE=vimeo

```
then I executed:
```
docker-compose run --rm laracastdl php ./start.php -s "servers-for-laravel"
```
However, videos were downloaded into the root folder, and also were comprised of two files:  m4a, and m4v
Since each were named using a UUID, it is impossible to know which two files belong to which series.

How can we  
1) ensure video is saved in the correct unique subfolder
2) ensure mp4 video is downloaded instead of two separate files for each video
3) have the filenames named by the episode name rather than a random UUID?

![image](https://github.com/carlosflorencio/laracasts-downloader/assets/19810611/4952e645-8591-4653-822d-6465e2a56bca)

**Comment by af-cl** [comment]
Hi @paulpreibisch , this solution helped me:
1. I removed DOWNLOAD_SOURCE from .env
2. I commented out line 160 in file App/Downloader.php

I hope this helps you too.

**Comment by eltoro0815** [comment]
I have the same issue.

How to reproduce?

**DOWNLOAD_SOURCE=vimeo**

Running on **Windows 11, WSL2, Ubuntu**

**docker-compose run --rm laracastdl php ./start.php**

**Comment by AmirRezaM75** [comment]
@paulpreibisch Can you test it again with latest version of master?
FFmpeg was not installed in docker file so it couldn't merge them.
