### ISSUE TITLE
Having issue on download

### ISSUE THREAD

**Issue by jaber-mtl** [carlosflorencio/laracasts-downloader#152]
@carlosflorencio 
![image](https://github.com/carlosflorencio/laracasts-downloader/assets/103347464/a4e12544-3cd1-4da0-82ab-a431e0a92411)

![image](https://github.com/carlosflorencio/laracasts-downloader/assets/103347464/a4027cb0-0b04-4923-b99f-83caaa1d07fa)

**Comment by carlosflorencio** [comment]
Yo, what do you need me to do?

**Comment by jaber-mtl** [comment]
> Yo, what do you need me to do?

Why I am getting this error?
