### ISSUE TITLE
ERROR: Client error response [url] https://laracasts.com [status code] 403 [reason phrase] Forbidden

### ISSUE THREAD

**Issue by Sotiris-k** [carlosflorencio/laracasts-downloader#154]
Hello,

Firstly thank you for this great tool, it's been really helpful for me to be able to watch laracasts videos offline and through my home media server.

Now to the issue at hand, today when I tried to do the daily check for any new videos I got the topic's error message.

`ERROR: Client error response [url] https://laracasts.com [status code] 403 [reason phrase] Forbidden`

Any thoughts?

**Comment by arjendevos** [comment]
This entire repo isn't working anymore. You can fix this error by adding an User-Agent to the headers and changing content-type to Content-Type & accept to Accept. 

However downloading with vimeo won't work

**Comment by carlosflorencio** [comment]
@Sotiris-k can you test if this fixes the issue? https://github.com/carlosflorencio/laracasts-downloader/pull/155 

Thanks @arjendevos

**Comment by Sotiris-k** [comment]
I've changed the occurrences of what @arjendevos mentioned in Http/Resolver.php but it didn't fix anything unfortunately.

**Comment by arjendevos** [comment]
@Sotiris-k did you install Proxyman?

**Comment by Sotiris-k** [comment]
I just noticed your PR @arjendevos . Made all the other changes you did in that PR but I didn't use Proxyman. I guess it must be a requisite.

**Comment by arjendevos** [comment]
@Sotiris-k weird workaround I know but it works (you need to enable SSL on laracast.com and player.vimeo.com in proxyman)

**Comment by Sotiris-k** [comment]
I don't think I can use Proxyman since I'm not on iOS and I'm running this utility through WSL

**Comment by nlmenke** [comment]
Some of us run this on headless servers (and/or on a cron schedule). If it can't be included in the docker image, a 3rd-party app requirement isn't an acceptable answer.

**Comment by arjendevos** [comment]
@nlmenke this isn't really a solution just a patch. The issue lies in the ssl certificates. You are free to fix the issue if you understand it

**Comment by nlmenke** [comment]
Looks like the issue (at least for the Laracasts side) is with Cloudflare's anti-bot system, so I guess the goal is to bypass that.

**Comment by AmirRezaM75** [comment]
Does the issue still exist?
I've just removed my cache file and start the script.
Both "**scrapping**" and "**downloading**" functionalities work fine.
(tested without subscription)

**Comment by nlmenke** [comment]
I just reran it locally (fresh repo, no changes) and everything works fine for me as well. I wonder if they just loosened the security on Cloudflare, but running this through both `docker compose ...` and `docker run ...` seem to be working as expected now.

**Comment by Sotiris-k** [comment]
Unfortunately for me the issue persists. Cache or no cache, same thing.

**Comment by AmirRezaM75** [comment]
I closed the issue, I downloaded all episodes in the pas few days with active subscription.

I the issue persists, we'll reopen it.
