### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by beyera** [carlosflorencio/laracasts-downloader#16]
# 
# Starting Collecting the data

> 216 new lessons and 496 episodes. 5.841s elapsed with 3.25Mb of memory usage.
# 
# Authenticating

> Successfull!
# 
# Downloading Lessons

> Download started: prevent-spam-with-recaptcha . . . . Saving on lessons folder.
> ERROR: Unable to open ./lessons/0216-prevent-spam-with-recaptcha.mp4 using mode r+: fopen(./lessons/0216-prevent-spam-with-recaptcha.mp4): failed to open stream: No such file or directory

**Comment by carlosflorencio** [comment]
Hi, try giving write permissions to the save folder. 

Sudo chmod 777 savefolder

**Comment by beyera** [comment]
went back and set perms set to 777 still having same problem, also it correctly creates the lessions folder

**Comment by carlosflorencio** [comment]
Sorry, try make it recursive to include lessons and series folder. 

sudo chmod 777 parentfolder -R

**Comment by beyera** [comment]
Yup tried, that. 99% sure even though it looks like a perms issue it's not.... even tried running everything as root with fully 777 perms

**Comment by beyera** [comment]
Figured it out. php5-curl wasn't installed. Recommend changing README to require php5-curl not just "curl" as command line curl can add confusion.

Thanks!

**Comment by carlosflorencio** [comment]
Nice! 

Will do that!
