### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by splifter** [carlosflorencio/laracasts-downloader#2]
I've setup your script like written in the README.
But no matter where i set the download folder or as which user ever i execute it, the script always returns the attached error. 

root@debian:~/laracasts-downloader# php start.php 
# 
# Starting Collecting the data

> 209 new lessons and 296 episodes. 17.904s elapsed with 3.25Mb of memory usage.
# 
# Authenticating

> Successfull!
# 
# Downloading Lessons

> Download started: email-verification-in-laravel . . . . Saving on lessons folder.
> ERROR: Unable to open /path_to_folder/laracast/lessons/0001-email-verification-in-laravel.mp4 using mode r+: fopen(/path_to_folder/laracast/lessons/0001-email-verification-in-laravel.mp4): failed to open stream: No such file or directory

Any idea whats going wrong?
Thanks for support!

**Comment by carlosflorencio** [comment]
Hi, do you have write permissions on the lessons folder?

**Comment by splifter** [comment]
Hi,
yes i had write permissions, path was created as root (incl. lessons and series folder) and script was also started as root.
Now i've deleted the sub-directories lessons and series et voilà it's running like a charm. Weird...

> Download started: email-verification-in-laravel . . . . Saving on lessons folder.
> Elapsed time: 109.354s, Memory: 4.00Mb
> Current: 1 of 209 total. Left: 208

Thank you very much for the amazing script!

**Comment by carlosflorencio** [comment]
Really weird!

Good to hear it works! Have fun!
