### ISSUE TITLE
Auth Issue

### ISSUE THREAD

**Issue by mark1282** [carlosflorencio/laracasts-downloader#21]
When running the script I received the message 'Your login details are wrong'. Upon inspection it turns out the issue was a special character in my password. 

The line: 

"$options = parse_ini_file('config.ini');" in boostrap.php was returning the password field as an empty string in the array because of this. 
I know this is down to parse_ini_file not liking special characters, but I was wondering if there was a solution for anyone else who comes across this issue.

**Comment by carlosflorencio** [comment]
Hi,

Quick dirty fix, change bootstrap.php:

`$options = parse_ini_file('config.ini');
$options["password"] = "password";`

Maybe in the future i will change this, but i think is not worth it.

**Comment by mark1282** [comment]
A quick solution I came up with was to require the env package using composer
'require vlucas/phpdotenv'
place the credentials in a .env file in the root and then call it in the bootstrap.php and inject it into the options array.

$options = array(); 

$dotenv = new Dotenv\Dotenv(**DIR**);
$dotenv->load();

$options['password'] = getenv('PASSWORD');
$options['email'] = getenv('EMAIL');
$options['local_path'] = getenv('LOCAL_PATH');
$options['lessons_folder'] = getenv('LESSONS_FOLDER');
$options['series_folder'] = getenv('SERIES_FOLDER');

May be overkill but could save someone having the same issue as myself. Great tool btw, I found it very useful as I don't always have a reliable internet connection.

**Comment by carlosflorencio** [comment]
Thanks for your solution.
