### ISSUE TITLE
Error on download

### ISSUE THREAD

**Issue by nacr** [carlosflorencio/laracasts-downloader#22]
Hello King :+1: 

Problem here when downloading I get a error like this,

`ERROR: cURL error 18: transfer closed with 41717430 bytes remaining to read`

Take note that I'm downloading `> Current: 43 of 217 total. Left: 174`

So the next file name should be 0174-*

But if I do php start.php the next file to be download gets the name 0260-*

How can I resolve this?

**Comment by carlosflorencio** [comment]
Hi,

The number for each lesson is total number of files in the lessons folder plus one.
So, you must have 259 files in that folder.
