### ISSUE TITLE
Had to run with sudo

### ISSUE THREAD

**Issue by camilo0365** [carlosflorencio/laracasts-downloader#23]
I assume it's an issue because the Readme does not mention execution with SUDO. This is what happens when running without SUDO using PHP7 in Ubuntu 16.04:
![screenshot](https://cloud.githubusercontent.com/assets/5257491/15578111/d0ce8aba-2324-11e6-9ca4-06303b4c56d8.png)

The script works when running with SUDO

**Comment by beyera** [comment]
Did you check to make sure the user has write access to the folder you have specified under "local_path" in the config.ini? It looks like your just using the laracasts-downloader folder so you should make sure it is writable or change the user:group to match the user launching the script.

Cheers.

**Comment by camilo0365** [comment]
That was the issue! My fault. Thanks!
