### ISSUE TITLE
ERROR: cURL error 7: Failed to connect to player.vimeo.com port 443: Operation timed out

### ISSUE THREAD

**Issue by Germey** [carlosflorencio/laracasts-downloader#24]
ERROR: cURL error 7: Failed to connect to player.vimeo.com port 443: Operation timed out
Hi, I got this problem, Could you tell me the reason?

**Comment by peinhu** [comment]
@Germey 'player.vimeo.com' is blocked by the GFW.

**Comment by Germey** [comment]
@peinhu No, I have opened shadowsocks of global mode. And I can visit 'vimeo.com' normally.

**Comment by peinhu** [comment]
@Germey You need VPN, I have had the same problem, but when I use the code on my VPS in other country, it works as normal, so it's the GFW‘s fault.

**Comment by troubleman** [comment]
@Germey  You can modify this file `App/Http/Resolver.php`  function `getRedirectUrl`, And add `proxy` config, This is my codes, and it worked well for me:

``` php
    private function getRedirectUrl($url)
    {
        $response = $this->client->get($url, [
            'cookies'         => $this->cookie,
            'allow_redirects' => FALSE,
            'verify' => false,
            'proxy' => [
                'http' => 'tcp://127.0.0.1:1080',
                'https' => 'tcp://127.0.0.1:1080'
            ]
        ]);

        return $response->getHeader('Location');
    }
```

**Comment by Germey** [comment]
@troubleman Wow! It works! Thank you!
