### ISSUE TITLE
cannot play video

### ISSUE THREAD

**Issue by ezekel** [carlosflorencio/laracasts-downloader#25]
Hi, after some lessons downloaded,I tried to play in vlc , but it looks like it cannot play the video, the vlc will get error. or do I need to wait to download all the 600 lessons so that I can play the video ?

Thank you in advance

**Comment by ezekel** [comment]
@iamfreee ,

The video being download is cannot be played in VLC, cannot recognize input format.

**Comment by carlosflorencio** [comment]
Hi, maybe because the website was updated.

I cannot test right now, i'm on vacation sorry.

**Comment by carlosflorencio** [comment]
@ezekel, can u see the size of the downloaded files? Can you open de file downloaded with notepad and see if it is html?

Can you upload it so i can debug it?

Thanks

**Comment by carlosflorencio** [comment]
@ezekel Did you entered a valid laracasts account?

**Comment by ezekel** [comment]
@iamfreee , oh I don't have laracasts account. so I need to register first does registering account is free?

**Comment by carlosflorencio** [comment]
Laracasts account is not free, you have to pay.
Closing this issue.
