### ISSUE TITLE
Downloads HTML Page.

### ISSUE THREAD

**Issue by pratham2003** [carlosflorencio/laracasts-downloader#28]
It downloads a HTML page.

**Comment by carlosflorencio** [comment]
Yeah, maybe the website was updated.

I dont have an active subscription to updated it right now.

**Comment by SumonMSelim** [comment]
@iamfreee do you need access to an active subscription to update it?

**Comment by carlosflorencio** [comment]
@SumonMSelim yes

**Comment by SumonMSelim** [comment]
@iamfreee If you want I can share mine for the purpose.

**Comment by carlosflorencio** [comment]
@SumonMSelim send me an email. i have time next tuesday 27.

**Comment by SumonMSelim** [comment]
@iamfreee email sent.

**Comment by carlosflorencio** [comment]
@pratham2003 @SumonMSelim Is working fine here.

All the files downloaded are HTML files or only some?
Can you show me the source of the file? 

Thanks

**Comment by carlosflorencio** [comment]
@pratham2003 Did you entered a valid laracasts account?

I fixed an issue right now.
