### ISSUE TITLE
only download file which has 29k and can not play 

### ISSUE THREAD

**Issue by Konizhang** [carlosflorencio/laracasts-downloader#29]
I download  all file from laracast but it all only has 29k .

**Comment by carlosflorencio** [comment]
@Konizhang will solve this after tomorow, sorry.

**Comment by teodoriu** [comment]
Is working for me. What is saying in that 29k file?

**Comment by carlosflorencio** [comment]
@Konizhang i tested right now and is working fine.

All the files downloaded are only 29k? Can you send one file for me to check?

Thanks

**Comment by Konizhang** [comment]
how to attach a file here or send you through email

**Comment by Konizhang** [comment]
those files seems html file . not real video files
