### ISSUE TITLE
New videos updater

### ISSUE THREAD

**Issue by techguydev** [carlosflorencio/laracasts-downloader#3]
Hello!, I just  wanted to  thanks fot  such an amazing tool!,  you  saved me  a lot  of  time  downloading the videos!

Is there a  way  that  we can set the system  to check when there are new videos available?

Thanks

**Comment by carlosflorencio** [comment]
Hi,  thanks for you feedback! 

Depending on your OS you have to search for a tool that can execute console commands periodically. 

On Linux maybe a cronjob, on Windows maybe scheduled tasks? 

Or you can subscribe to laracasts rss feed and when there is a new vídeo you run the tool.

**Comment by techguydev** [comment]
Excellent, thanks a lot I will do.

Keep  up the good  work!

**Comment by carlosflorencio** [comment]
You too, closing.
