### ISSUE TITLE
How to download specific series?

### ISSUE THREAD

**Issue by dev-myatminsoe** [carlosflorencio/laracasts-downloader#30]
Hello, I want to download a serie not the whole lessons. How can I do that?

**Comment by carlosflorencio** [comment]
@septemberboy7  I need a subscription to add that feature.
If someone can provide it i would appreciate it.

**Comment by dev-myatminsoe** [comment]
Sorry that I don't have a subscription too. I'm using it for downloading free tutorials

**Comment by carlosflorencio** [comment]
Feature added by pull request
