### ISSUE TITLE
laracasts refresh

### ISSUE THREAD

**Issue by spoonwep** [carlosflorencio/laracasts-downloader#32]
Laracasts brings a refresh today and laracasts-downloader doesn't work.
Hope there's a new release soon,thank you :)

**Comment by fmulyono** [comment]
I submited PR #33 about this.
Could you verify it's working?

**Comment by spoonwep** [comment]
@fmulyono still not working

**Comment by fmulyono** [comment]
Can you share the error message or some screenshots?
I'm currently downloading using the patched code :)

**Comment by spoonwep** [comment]
@fmulyono 
![screenshot](https://cloud.githubusercontent.com/assets/4607506/20342472/7aa90cde-ac25-11e6-968d-ecaa1deae0f0.jpg)

**Comment by fmulyono** [comment]
My bad, wrong class name.
Updated the PR. Could you try it again?

**Comment by carlosflorencio** [comment]
Thanks for the effort @fmulyono.

@spoonwep Let me know if the fix works to merge the @fmulyono pull request.

**Comment by spoonwep** [comment]
@iamfreee @fmulyono 
It works fine now,thankyou for your help :)

**Comment by carlosflorencio** [comment]
Thanks @fmulyono
