### ISSUE TITLE
Add ability to retry download

### ISSUE THREAD

**Issue by antonkomarev** [carlosflorencio/laracasts-downloader#34]
Sometimes on bad internet connection download is interrupting:

> ERROR: cURL error 7: Failed to connect to laracasts.com port 443: Network is unreachable

or 

> ERROR: cURL error 6: Could not resolve host: 10-lvl3-pdl.vimeocdn.com

It will be great to have RETRY_COUNT in config, by default is 1. If value is greater than 1 it will retry download process on these cURL errors without interrupting all the process. Or have an ability to launch `start.php` with `--retry` flag.

**Comment by carlosflorencio** [comment]
Hi,

I don't have time to implement that right now. So it has to be a pull request. 😞

**Comment by antonkomarev** [comment]
@iamfreee Added PR.

**Comment by antonkomarev** [comment]
Just FYI, I've found a better way to make http client retries on connection issues: https://github.com/guzzle/retry-subscriber
By using it there is a way to describe retry strategy and make it globally in a clean way.

**Comment by carlosflorencio** [comment]
@a-komarev yep, thanks. 
I'm working with nodejs at the moment, i don't know when i will work with php again. So i will accept pull requests but i don't pretend to add new features in the near future.
