### ISSUE TITLE
videos that are being downloaded have only 290kB size

### ISSUE THREAD

**Issue by Abu-Zakaria** [carlosflorencio/laracasts-downloader#42]
I started downloading a series. After download was complete, i got some files which is 290kB  in size and they are .mp4 file....
Please fix this!

I am attaching a .zip file which contains all of the videos....

[incremental-api-development.tar.gz](https://github.com/iamfreee/laracasts-downloader/files/736981/incremental-api-development.tar.gz)

**Comment by carlosflorencio** [comment]
Hi,

Do you have a paid subscription? You must have one to download the videos.
I have pushed a commit today that prevents downloading lessons without a valid account.

**Comment by Abu-Zakaria** [comment]
oh, that's the case!
I dont have any subscription....

**Comment by carlosflorencio** [comment]
Yep, thats the problem.

**Comment by olimortimer** [comment]
Is this the same for the free lessons?  Ie https://laracasts.com/series/laravel-from-scratch-2017/
