### ISSUE TITLE
Downloaded files are just 94KB and do not contain video content

### ISSUE THREAD

**Issue by Mexx77** [carlosflorencio/laracasts-downloader#43]
Hey,

my downloaded files are just 94KB and do not contain video content? I run the command
`php start.php -s "learn-vue-2-step-by-step"`
it lists all 30 sessions and downloads them to my local folder. But they are too small and do not contain video content.

Any idea?

Cheers, Max

I attached the terminal output.
[output.txt](https://github.com/iamfreee/laracasts-downloader/files/785932/output.txt)

**Comment by carlosflorencio** [comment]
Do you have a valid account & subscription active?

**Comment by Mexx77** [comment]
no, but it is a free series I am trying to download.

2017-02-19 18:15 GMT+01:00 Carlos Florêncio <notifications@github.com>:

**Comment by carlosflorencio** [comment]
You are only allowed to download episodes if you a valid subscription i think.
