### ISSUE TITLE
videos are downloading descending order

### ISSUE THREAD

**Issue by ashickurnoor** [carlosflorencio/laracasts-downloader#44]
Your library is cool for user like me, who have limited internet speed. How ever when I start downloading a series, videos are downloading descending order, I mean last video of the series is downloading first.  I don't know is it a bug or not?  It will be better if you can make it downloading ascending order.

**Comment by carlosflorencio** [comment]
Hi,

Is not a bug, but it was never a concern. I will reverse the order tomorrow if i can.. 😃

**Comment by carlosflorencio** [comment]
Reversed the order of the episodes download from low to high.
