### ISSUE TITLE
wrong lesson is downloaded

### ISSUE THREAD

**Issue by ashickurnoor** [carlosflorencio/laracasts-downloader#45]
Hi

I was trying to download this [lesson](https://laracasts.com/lessons/php-password-hashing) . When I tried with cli with this 
`php start.php -l " PHP's Password Hashing API" -l "php-password-hashing"`

wrong lesson is downloaded. Log is attached
[download-log.txt](https://github.com/iamfreee/laracasts-downloader/files/809422/download-log.txt)
.

**Comment by carlosflorencio** [comment]
Hi,

I just fixed, try again with the new version.

Thanks

**Comment by ashickurnoor** [comment]
It is working fine now.
