### ISSUE TITLE
can we put in content into specific directory?

### ISSUE THREAD

**Issue by cyberhck** [carlosflorencio/laracasts-downloader#46]
so let's say I want do download everything for offline usage, can we auto sync into different directories series wise? 

BTW: I liked your terminal style info in your gh-pages webpage 👍

**Comment by carlosflorencio** [comment]
Hi,

Can you specify?

Currently you can choose the download folder like this:

```
~/Laracasts  (you can modify the path for this folder)
                  /lessons -> all lessons episodes (you can modify this folder name)
                  /series    -> series are in sub-folders  (you can modify this folder name)
```

**Comment by cyberhck** [comment]
sorry, I confused series with lessons, it's downloading everything to lessons, was waiting for a series directory 😄  Thanks!
