### ISSUE TITLE
SLL error:  cURL error 35

### ISSUE THREAD

**Issue by lucassmacedo** [carlosflorencio/laracasts-downloader#48]
I have a problem..  with php7.0.8
The log:

====================================
Authenticating
====================================
> Successfull!

====================================
Starting Collecting the data
====================================

====================================
Checking for options []
====================================
> No options provided

====================================
Downloading
====================================
> 0 new lessons and 24 episodes. 9.626s elapsed with 6.00Mb of memory usage.

====================================
Downloading Series
====================================

> Download started: 17 - How Do I Impersonate Users . . . . Saving on series/how-do-i folder.
> Total: 0% Downloaded: 0 B of 0 B     
> Retry download after connection fail!     
> Total: 0% Downloaded: 0 B of 0 B     
> Retry download after connection fail!     
> Total: 0% Downloaded: 0 B of 0 B     
> Retry download after connection fail!     
ERROR: cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version%

**Comment by carlosflorencio** [comment]
Can you try changing the guzzle code to this:
http://stackoverflow.com/a/19259023/2741122

It is working fine in my windows 10 setup.

**Comment by lucassmacedo** [comment]
No success.. On mac

**Comment by carlosflorencio** [comment]
Tested on windows 10 with php 7 and works fine too. (my previous test was with v5.6)

In the weekend i can test with ubuntu and php7 on docker if you can't find a workaround i suggest you use docker.

**Comment by lucassmacedo** [comment]
Solved!

**Comment by carlosflorencio** [comment]
How? 😄

**Comment by lucassmacedo** [comment]
I have added add the cacert.pem =D

**Comment by carlosflorencio** [comment]
Ahh nice! 😃
