### ISSUE TITLE
videos broken

### ISSUE THREAD

**Issue by bashman** [carlosflorencio/laracasts-downloader#49]
Edit:

When I try to resume the download, the last video is broken.  

`EMAIL=xxx@gmail.com
PASSWORD=xxx
LOCAL_PATH=Downloads
LESSONS_FOLDER=lessons
SERIES_FOLDER=series
TIMEZONE=America/Caracas
RETRY_DOWNLOAD=true
`

**Comment by carlosflorencio** [comment]
Hi, 

I din't get your question, if a downloading fails you get a corrupt video file yes. Delete it, and run the script to download it again.

**Comment by bashman** [comment]
Ummm, but wget and curl have functions to resume the video download, if  the token not expires. 

I can manually resume the download:
bashman$wget -c -T0 https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/262/8/201312601/681022035.mp4?token=xxxx&download=1&filename=10-Layouts-and-Structure.mp4  

if you download whole the site "php start.php", is a hard work view video by video...

**Comment by carlosflorencio** [comment]
I see, but this was the design i choosed at the time.
As i don't have internet problems i didn't tought of edge cases.

I don't have the time to invest in this now, maybe in the future i can make a new version with concurrent downloads and another features. But not now.

You can do a pull request with the features you need.
