### ISSUE TITLE
New website layout breaks downloader

### ISSUE THREAD

**Issue by nicozimmermann94** [carlosflorencio/laracasts-downloader#5]
I think the redesing broke your downloader. I am getting the following error:
***Notice: Undefined index: series in D:\Laracasts\laracasts-downloader\App\Utils\U
tils.php on line 85

Warning: Invalid argument supplied for foreach() in D:\Laracasts\laracasts-downl
oader\App\Utils\Utils.php on line 85

Notice: Undefined index: lessons in D:\Laracasts\laracasts-downloader\App\Utils\
Utils.php on line 101

Warning: array_diff(): Argument #1 is not an array in D:\Laracasts\laracasts-dow
nloader\App\Utils\Utils.php on line 101

---

**Comment by carlosflorencio** [comment]
Hi, 

Will look into it today, thanks.

**Comment by carlosflorencio** [comment]
Updated to work with the new design.

Try again.

**Comment by nicozimmermann94** [comment]
Hm getting this now:

Authenticating

ERROR: Server error response [url] https://laracasts.com/dashboard [status code]
 500 [reason phrase] Internal Server Error

Maybe it is because my subcription ends today or tomorrow.

**Comment by carlosflorencio** [comment]
Can you check if your subcription is active, because i didnt test that case.

**Comment by kossa** [comment]
Today I got the same error:

Warning: Invalid argument supplied for foreach() in /Users/mac/code/laracasts-downloader/App/Utils/Utils.php on line 85

Warning: array_diff(): Argument #1 is not an array in /Users/mac/code/laracasts-downloader/App/Utils/Utils.php on line 101
