### ISSUE TITLE
Bug in Mac/Mamp

### ISSUE THREAD

**Issue by kossa** [carlosflorencio/laracasts-downloader#50]
Hello,

I worked with archlinux, php7 ...etc it worked fine now I'm with:
Os : Mac sierra
MAMP : Php 7.1

when I run in console : `php start.php` I get nothing, I tried in browser I get : `Fatal error: Uncaught League\Flysystem\Exception: Impossible to create the root directory "". in /Users/mac/code/laracasts-downloader/vendor/league/flysystem/src/Adapter/Local.php:106 Stack trace: #0 /Users/mac/code/laracasts-downloader/vendor/league/flysystem/src/Adapter/Local.php(78): League\Flysystem\Adapter\Local->ensureDirectory(false) #1 /Users/mac/Code/laracasts-downloader/start.php(14): League\Flysystem\Adapter\Local->__construct(false) #2 {main} thrown in /Users/mac/code/laracasts-downloader/vendor/league/flysystem/src/Adapter/Local.php on line 106`

Why this issue ?

**Comment by carlosflorencio** [comment]
Hi @kossa,

After reading the exception, it seems a directory problem. Are the folders with the right write permissions?

Do you have valid paths in your .env file?

**Comment by kossa** [comment]
The path is correct look :

<img width="1114" alt="2017-06-13_0005" src="https://user-images.githubusercontent.com/1175584/27059025-4e31a684-4fcc-11e7-85f5-100b2c9338a1.png">

**Comment by kossa** [comment]
My bad I found the issue, PATH and not PAT

Sorry :(

**Comment by carlosflorencio** [comment]
No problem 😃
