### ISSUE TITLE
Series not downloaded correctly

### ISSUE THREAD

**Issue by envomer** [carlosflorencio/laracasts-downloader#52]
Hi,

i have been trying to download the latest episodes of a laracasts series but for some reason it doesn't work.

```
> Download started: 70 - Thread Views Design 3 - KISS . . . . Saving on series/lets-build-a-forum-with-laravel folder.
> Can't download this lesson! :( No download button
> Tring to find a Wistia.net video
> Elapsed time: 147ms, Memory: 4.00Mb
> Current: 6 of 6 total. Left: 0
```

A 70K file is downloaded instead.
```
-rw-r--r-- 1 root root  70K Aug 22 21:57 70-Thread Views Design 3 - KISS.mp4
```

I am using a valid laracasts premium account. Any idea why that's the case? Any help is appreciated.

**Comment by carlosflorencio** [comment]
Just tried now and is working.

Are u sure your account is valid and active? confirm your `.env` file

**Comment by envomer** [comment]
Oh i just saw you made an update 2 weeks ago...Guess i was a little outdated. Works now. Thanks a bunch for this epic tool 👍
