### ISSUE TITLE
Not all episodes were retrieved

### ISSUE THREAD

**Issue by TinoN** [carlosflorencio/laracasts-downloader#54]
Hello,
I'm not sure if this is a problem with the Downloader, but I just tried downloading [Let's build a forum with Laravel](https://laracasts.com/series/lets-build-a-forum-with-laravel).
Apparently only 67 out of 70 episodes were found.
![170824_download_episodes](https://user-images.githubusercontent.com/1530296/29651740-cabf31b2-88d4-11e7-8d53-29213709f8f6.png)

used: `php start.php -s "lets-build-a-forum-with-laravel"` for downloading

Also just double checked with [Professional PHP Workflow...](https://laracasts.com/series/professional-php-workflow-in-sublime-text).
Here only 6 out of 11 episodes were found.
![170824_download_episodes2](https://user-images.githubusercontent.com/1530296/29651958-e1a4ae6a-88d5-11e7-8aeb-90826d197772.png)

used: `php start.php -s "professional-php-workflow-in-sublime-text"`

Regards!

**Comment by carlosflorencio** [comment]
Hi,

Can you check if you have the series folder empty or a .skip file? If so remove it.

I tried now and it detects fine 70 episodes, maybe you have local files already.

**Comment by TinoN** [comment]
Hi,
no .skip file found. I also didn't empty the folder but I just tried the command today again and the missing episodes were found and downloaded. Don't know why it didn't work last week, although I tried the command a couple of times.
Cheers!
