### ISSUE TITLE
size of videos not actual, only 70kb

### ISSUE THREAD

**Issue by blackinitial** [carlosflorencio/laracasts-downloader#55]
I'm was sucessfullly to download videos series "Learn Vue 2: Step By Step".
```bash
> Download started: 33 - Scoped Slots . . . . Saving on series/learn-vue-2-step-by-step folder.
> Elapsed time: 465ms, Memory: 4.00Mb         
> Current: 33 of 33 total. Left: 0
> Finished! Downloaded 0 new lessons and 33 new episodes. Failed: 0
```

but, size of video only 70,7 kb..
<a href="http://i.imgur.com/ktspbqJ.png">
  <img src="http://imgur.com/ktspbqJl.png" />
</a>
what's happen??

**Comment by carlosflorencio** [comment]
Do you have a valid account with an active subscription?

**Comment by blackinitial** [comment]
I have registered in laracast, my email n pass in .env is also true..

**Comment by blackinitial** [comment]
owh, must be paid subscribers .. :disappointed_relieved:

**Comment by carlosflorencio** [comment]
Yep 😄

**Comment by blackinitial** [comment]
thanks
