### ISSUE TITLE
Downloading home page HTML content (~70 kB)

### ISSUE THREAD

**Issue by ghost** [carlosflorencio/laracasts-downloader#56]
Firstly I'd like to thank you for providing such a tool for us.

I'm currently using it with Docker and I've followed the instructions in the `README.md` file. Yet the script outputs the following for all files:

```
> Download started: how-to-use-gzipping-to-decrease-file-sizes-by-seventy-five-percent . . . . Saving on lessons folder.
> Can't download this lesson! :( No download button
> Tring to find a Wistia.net video
> Elapsed time: 315ms, Memory: 4.00Mb         
> Current: 1 of 213 total. Left: 212
```

It ends up downloading the home page HTML content (a file with a size of 70 kB - give or take).

I have an active subscription, by the way.

**Comment by carlosflorencio** [comment]
Hi,

The download link was updated in the page.

Last commit b29f6e61a1f58464971957eb84affbd9c313efb9 should fix this.

😃

**Comment by ghost** [comment]
Thank you very much, @iamfreee.

**Comment by runo280** [comment]
I'm getting the same result, 70kb html files with mp4 ext.

Output:
`====================================
Authenticating
====================================
> Successfull!

====================================
Starting Collecting the data
====================================

====================================
Checking for options {"s":"laravel-from-scratch-2017"}
====================================
> Series names provided: ["laravel-from-scratch-2017"]
> Series names provided: ["laravel-from-scratch-2017"]

====================================
Checking if series and lessons exists
====================================
> Series "laravel-from-scratch-2017" found!

====================================
Downloading
====================================
> 0 new lessons and 32 episodes. 1.385s elapsed with 4.00Mb of memory usage.

====================================
Downloading Series
====================================

> Download started: 01 - Laravel Installation and Composer . . . . Saving on series/laravel-from-scratch-2017 folder.
> Elapsed time: 35ms, Memory: 4.00Mb         
> Current: 1 of 32 total. Left: 31

> Download started: 02 - Basic Routing and Views . . . . Saving on series/laravel-from-scratch-2017 folder.
> Elapsed time: 27ms, Memory: 4.00Mb         
> Current: 2 of 32 total. Left: 30`
