### ISSUE TITLE
not picking up latest episode

### ISSUE THREAD

**Issue by vesper8** [carlosflorencio/laracasts-downloader#58]
Just ran a download.. this is the bash file I use to download all the latest videos on all series I'm watching

```
#!/usr/bin/env bash

series='
-s "professional-php-workflow-in-sublime-text"
-s "whats-new-in-laravel-5-5"
-s "laravel-from-scratch-2017"
-s "learn-vue-2-step-by-step"
-s "php-for-beginners"
-s "whatcha-working-on"
-s "whats-new-in-laravel-5-4"
-s "whats-new-in-php-7-1"
-s "how-do-i"
-s "lets-build-a-forum-with-laravel"
-s "php-bits"
-s "git-me-some-version-control"
'

php start.php ${series}
```

it picked up a few new videos and all seemed to work fine

except there's an oddity.. the whatcha-working-on series has a 24th episode and it's not downloading it.. there's only 23 in the folder.. the 24th is watchable and released but it's not being picked up as of right now.. any idea why ?

**Comment by carlosflorencio** [comment]
Hi,

Can you try downloading now? Maybe it was a temporary issue the episode not included the listings. (Cache?)

Thanks

**Comment by vesper8** [comment]
Just tried it again, again it didn't find the 24th episode

And I checked in the series' folder to make sure there isn't an incomplete file or a skip file

no idea why this is happening

**Comment by carlosflorencio** [comment]
![image](https://user-images.githubusercontent.com/1500881/31436863-1f1d167c-ae7b-11e7-8d5b-0293490886e8.png)
![image](https://user-images.githubusercontent.com/1500881/31436870-248c7c60-ae7b-11e7-8341-818bf4ae9a41.png)

Worked here. Can you try running the command with just the `whatcha-working-on` serie?

Also, try changing the path of your series folder to another location. 

If it didn't work, try debbuging these arrays:
https://github.com/iamfreee/laracasts-downloader/blob/master/App/Downloader.php#L94
https://github.com/iamfreee/laracasts-downloader/blob/master/App/Downloader.php#L95
https://github.com/iamfreee/laracasts-downloader/blob/master/App/Downloader.php#L109

**Comment by carlosflorencio** [comment]
no more info
