### ISSUE TITLE
Downloaded was not playing.

### ISSUE THREAD

**Issue by risurina** [carlosflorencio/laracasts-downloader#59]
I was downloading using command { php start.php -s "Series name example" -s "series-slug-example" }
(without curly brackets ) then it says that download was completed, but when i try to play the .mp4 files it was not playing.

Thank's!

**Comment by carlosflorencio** [comment]
More info?

**Comment by risurina** [comment]
I was downloading using command  { php start.php -s "Series name example" -s "series-slug-example" }
(without curly brackets ) then it says that download was completed, but when i try to play the .mp4 files it was not playing.

Thank's!

**Comment by carlosflorencio** [comment]
Do you have a valid account with an active subscription?

**Comment by risurina** [comment]
No, I don't have any subscription.

**Comment by carlosflorencio** [comment]
You need a valid subscription, that's the reason.
