### ISSUE TITLE
Download a specific episode in a serie

### ISSUE THREAD

**Issue by kossa** [carlosflorencio/laracasts-downloader#60]
Hello,

Is it possible to download one episode not all the serie ? like episode 14 in the 'lets-build-a-forum-with-laravel' serie.

Thanks

**Comment by carlosflorencio** [comment]
Hi, is not possible you have to download all episodes of the serie.

**Comment by kossa** [comment]
aha I see,

Today I had a connection issue when I downloading a serie, the last episode not completely downloaded, so I want only to download this episode

**Comment by carlosflorencio** [comment]
Just delete the file, and run the tool again it will download the remaining episodes.
