### ISSUE TITLE
Only downloads the video file but NOT exactly the video

### ISSUE THREAD

**Issue by jonjie0317** [carlosflorencio/laracasts-downloader#61]
Hi, I downloaded all the video of a series but it is just 133KB file, not the exact video. Why is that?

**Comment by carlosflorencio** [comment]
Do you have a valid subscription?

**Comment by jonjie0317** [comment]
I just have an account, but not have any subscription. Is that required?  Even if I just want to download the free videos/series?  I just want to download free videos, not the paid videos.

**Comment by carlosflorencio** [comment]
Yes, if you try to download the free series you can't because you need a valid subscription :/.

That is the issue here.

**Comment by jonjie0317** [comment]
Oh this means that this project is for users with subscription ONLY, then you might have to put it in the documentation so they know that they have to subscribe first before using it. Thanks :)

**Comment by carlosflorencio** [comment]
Is already in the README ehehe.

https://github.com/iamfreee/laracasts-downloader#an-account-with-an-active-subscription-is-necessary
