### ISSUE TITLE
How can I run this as a background job in a headless linux machine?

### ISSUE THREAD

**Issue by ronaklodaya** [carlosflorencio/laracasts-downloader#62]
I want to run this tool as a background a linux environment, how can I achieve this?

I have my router which is running openwrt (a linux distro) and I want to download the whole content.

**Comment by carlosflorencio** [comment]
This tool requires PHP to run, so you have to install php in your linux machine.

To run in the background you can schedule a cron job or use screen to run the process in the background (if you connect via ssh).
