### ISSUE TITLE
an option to download free series for non registered users?

### ISSUE THREAD

**Issue by a-eid** [carlosflorencio/laracasts-downloader#64]

**Comment by carlosflorencio** [comment]
The download button in the website does not work without a valid subscription.

**Comment by a-eid** [comment]
Got it 
Thanks.

**Comment by gbdematos** [comment]
You can use youtube-dl.

**Comment by carlosflorencio** [comment]
@gbdematos can you elaborate? These videos are on youtube?

**Comment by gbdematos** [comment]
Oops. Sorry.

No, the videos are stored on vimeo, and YouTube-DL has a generic extractor that works on most websites besides youtube, including Laracasts.  I used to use it before (to download free videos ofc).

**Comment by carlosflorencio** [comment]
Ah okay 😄
