### ISSUE TITLE
Only files with lesson names creates under series/series name folder - no actual video is downloaded

### ISSUE THREAD

**Issue by hafizc007** [carlosflorencio/laracasts-downloader#65]

**Comment by carlosflorencio** [comment]
Please give more details.
Do you have a valid subscription?

**Comment by hafizc007** [comment]
![screenshot 1](https://user-images.githubusercontent.com/28489834/34361536-f361ff64-ea90-11e7-86cb-ddfacec5adee.png)

Iam trying with a free series
see --> 
![screenshot 3](https://user-images.githubusercontent.com/28489834/34361555-231f9bf8-ea91-11e7-92b8-67969d34653b.png)

i got every file list. but as you can see in this image every file is 136kb 
![screenshot 4](https://user-images.githubusercontent.com/28489834/34361593-6ef444a2-ea91-11e7-95f3-6ef00d7ce858.png)
 please help me. it will be really help full since i cant afford streaming till it completes ..Thank you

**Comment by carlosflorencio** [comment]
Sorry but to download any lesson a valid subscription is required.
This tool can't download free lessons without an account.

**Comment by hafizc007** [comment]
actually i have a account and updated it in .env file and subscribed too

**Comment by carlosflorencio** [comment]
With an active subscription? (paid month)

**Comment by sysblade** [comment]
Maybe it could chek the returned content-type to warn of missing subscription ? As for now the mp4 files contain the page's html.

**Comment by carlosflorencio** [comment]
@kedare yep, it is a nice addition.

Current check: https://github.com/iamfreee/laracasts-downloader/blob/5a764c7e4abbd47ed0f2e4d425422b0ab674fcee/App/Http/Resolver.php#L144

Is not enough.
