### ISSUE TITLE
File numbering problem

### ISSUE THREAD

**Issue by bansalvinay** [carlosflorencio/laracasts-downloader#67]
Hi, Thanks for this nice package. However I was facing a small difficulty. The videos in lessons forlder are numbered in descending order. But when there is problem in one video, and I restart it, the numbering order changes completely. Now I have downloaded many videos and some of them were corrupt and I deleted them. Now when I try to download them, the program can't identify any new videos.

**Comment by carlosflorencio** [comment]
Hi,

Are you using `makeskips.php`? 
Asking because if you delete a video or a serie folder, the script should download all the lessons in descending order.

**Comment by carlosflorencio** [comment]
This seems an edge case about lessons, i don't have time to investigate it now.
If you want to fix the problem i am happy to merge the pull request.

🙂
