### ISSUE TITLE
app does not continue with the interrupted download.

### ISSUE THREAD

**Issue by SapneshNaik** [carlosflorencio/laracasts-downloader#68]
If the download process fails due some reasons such as a drop in internet connection. The next time when you restart the process the next file is picked for download and the previously interrupted download is not continued. Leaving the interrupted video file incomplete.

Is there any way to solve this?

Perhaps compare a hash of the last file and restart the file if the hashes do not match?

**Comment by carlosflorencio** [comment]
The only way, for now, is to delete those files and run the script again (missing files will be downloaded).

Just delete the files with the smallest size.
