### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by altraWeb** [carlosflorencio/laracasts-downloader#69]
```bash
====================================
Authenticating
====================================
ERROR: Client error response [url] https://laracasts.com/dashboard [status code] 404 [reason phrase] Not Found
```

Any help?? Thanks

**Comment by carlosflorencio** [comment]
Hi,

This seems to be an issue with the website, if you try to login via https://laracasts.com/login you will be redirected to a `/dashboard` path which gives a 404.

**Comment by altraWeb** [comment]
Yes. And is there a way to fix that?

**Comment by carlosflorencio** [comment]
Just sent a message via https://laracasts.com/contact to see if the site owner fixes the issue.

In the meantime, you can add an ad hoc fix to the file https://github.com/carlosflorencio/laracasts-downloader/blob/master/App/Http/Resolver.php#L142, try adding a try catch to ignore the authentication result.

**Comment by shaulhaf** [comment]
working now.

**Comment by carlosflorencio** [comment]
Great! closing this
