### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sikrew** [carlosflorencio/laracasts-downloader#7]
Somehow I'm getting this error whenever I try to download. The workaround I've found is to use an earlier version of `guzzle`. I'm using version 4.2.3 ( ~4.0 )

Updating `composer.json` and running `composer update` seems to fix it.

Any idea of what's happening?

**Comment by KuenzelIT** [comment]
I had the same problem, "fixing" it by disabling ssl temporarily.

**Comment by sikrew** [comment]
Can you please describe how you worked around the issue? It might be helpful to others and to @iamfreee to solve the issue

**Comment by KuenzelIT** [comment]
If you mean my comment, I just deactivated ssl in guzzle as described in the documentation:
http://guzzle.readthedocs.org/en/5.3/clients.html#verify-option

**Comment by sikrew** [comment]
Yes, I was referring to your workaround. Thanks! It might help someone out

**Comment by carlosflorencio** [comment]
I will look into this problem soon.. Maybe this weekend, but the downloader is working right?

**Comment by sikrew** [comment]
Yes the downloader is working as expected

**Comment by carlosflorencio** [comment]
Okay :smile:

**Comment by carlosflorencio** [comment]
Hi again, i just removed the secure requests from curl.

Should prevent this error in the future.

Closing
