### ISSUE TITLE
Indication of download size before downloding

### ISSUE THREAD

**Issue by noobling** [carlosflorencio/laracasts-downloader#70]
Thank you for this application,

Do you think it would be a good idea to give an indication of the download size before committing to a download e.g.
```
$ php start.php
> Download Size: 5gb
> Do you wish to proceed?
```
Something like that?

**Comment by carlosflorencio** [comment]
Supposing you have N new videos to download, you would have to open N connections just to see the size of each video (PHP isn't asynchronous yet, that would take time).

Don't think this overhead is justified as it gives little benefit. 
Instead, you can calculate some estimates assuming an average size of each video, like for example 22 videos to download would be `22 * 80MB = ~1.8GB`.

**Comment by noobling** [comment]
Alright thank you, maybe a rough estimation is possible? Would it be more accurate to use the length of the video to calculate the approx size? Not sure if you get that data while finding the number of videos.

**Comment by carlosflorencio** [comment]
Yep, you can work with the video length since it's alongside with the lesson name, just have to scrape it as well.

If you want to make a Pull Request I'll be happy to review it 😃.

**Comment by carlosflorencio** [comment]
No updates, closing.
