### ISSUE TITLE
How to clear cache ?

### ISSUE THREAD

**Issue by kossa** [carlosflorencio/laracasts-downloader#71]
Hello,

I have 2 episodes missed from a serie after losing internet connection, when I try to download them i get : 0 episodes

There is a way to force the command to check all series ?

Thank you

**Comment by carlosflorencio** [comment]
Hi,

Confirm that those episodes do not exist in the filesystem, and there are no .skip files in the directory.

**Comment by kossa** [comment]
Look:
![image](https://user-images.githubusercontent.com/1175584/41204339-1c65dff8-6cdb-11e8-8bcd-f0a4f491bb27.png)


![image](https://user-images.githubusercontent.com/1175584/41204406-fbd161bc-6cdb-11e8-92bc-03c760e478ba.png)

**Comment by carlosflorencio** [comment]
I just tried and it worked, even disconnected from the internet.
Check if there are no hidden files in that directory, and try deleting one lesson and downloading it again.

**Comment by kossa** [comment]
I'm sure there is no hidden file, very strange, and I have the latest commit 

I deleted the episode 09 it works fine, very strange :p

**Comment by carlosflorencio** [comment]
Good to know 👍
