### ISSUE TITLE
New website layout breaks downloader "2018"

### ISSUE THREAD

**Issue by cerberos** [carlosflorencio/laracasts-downloader#74]
Jeff updates the layout and the downloader is not working anymore:

PHP Notice:  Undefined index: series in D:\tutorials\laracasts-downloader-master-08-08-2018\App\Utils\Utils.php on line 85
PHP Stack trace:
PHP   1. {main}() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:0
PHP   2. App\Downloader->start() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:23
PHP   3. App\Utils\Utils::resolveFaultyLessons() D:\tutorials\laracasts-downloader-master-08-08-2018\App\Downloader.php:109

Notice: Undefined index: series in D:\tutorials\laracasts-downloader-master-08-08-2018\App\Utils\Utils.php on line 85

Call Stack:
    0.4058     384880   1. {main}() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:0
    0.4519    1870880   2. App\Downloader->start() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:23
    2.4998    3218224   3. App\Utils\Utils::resolveFaultyLessons() D:\tutorials\laracasts-downloader-master-08-08-2018\App\Downloader.php:109

Variables in local scope (#3):
  $array = array ('series' => array (), 'lessons' => array ())
  $episode = *uninitialized*
  $episodes = *uninitialized* ...........................

**Comment by agarzon** [comment]
I was just about to report the same ;)

```
Downloading
====================================
PHP Notice:  Undefined index: series in /home/agarzon/GIT/laracasts-downloader/App/Utils/Utils.php on line 85
PHP Stack trace:
PHP   1. {main}() /home/agarzon/GIT/laracasts-downloader/start.php:0
PHP   2. App\Downloader->start() /home/agarzon/GIT/laracasts-downloader/start.php:23
PHP   3. App\Utils\Utils::resolveFaultyLessons() /home/agarzon/GIT/laracasts-downloader/App/Downloader.php:109
PHP Warning:  Invalid argument supplied for foreach() in /home/agarzon/GIT/laracasts-downloader/App/Utils/Utils.php on line 85
PHP Stack trace:
PHP   1. {main}() /home/agarzon/GIT/laracasts-downloader/start.php:0
PHP   2. App\Downloader->start() /home/agarzon/GIT/laracasts-downloader/start.php:23
PHP   3. App\Utils\Utils::resolveFaultyLessons() /home/agarzon/GIT/laracasts-downloader/App/Downloader.php:109
PHP Notice:  Undefined index: lessons in /home/agarzon/GIT/laracasts-downloader/App/Utils/Utils.php on line 101
PHP Stack trace:
PHP   1. {main}() /home/agarzon/GIT/laracasts-downloader/start.php:0
PHP   2. App\Downloader->start() /home/agarzon/GIT/laracasts-downloader/start.php:23
PHP   3. App\Utils\Utils::resolveFaultyLessons() /home/agarzon/GIT/laracasts-downloader/App/Downloader.php:109
PHP Warning:  array_diff(): Argument #1 is not an array in /home/agarzon/GIT/laracasts-downloader/App/Utils/Utils.php on line 101
PHP Stack trace:
PHP   1. {main}() /home/agarzon/GIT/laracasts-downloader/start.php:0
PHP   2. App\Downloader->start() /home/agarzon/GIT/laracasts-downloader/start.php:23
PHP   3. App\Utils\Utils::resolveFaultyLessons() /home/agarzon/GIT/laracasts-downloader/App/Downloader.php:109
PHP   4. array_diff() /home/agarzon/GIT/laracasts-downloader/App/Utils/Utils.php:101
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/agarzon/GIT/laracasts-downloader/App/Utils/Utils.php on line 51
PHP Stack trace:
PHP   1. {main}() /home/agarzon/GIT/laracasts-downloader/start.php:0
PHP   2. App\Downloader->start() /home/agarzon/GIT/laracasts-downloader/start.php:23
PHP   3. App\Utils\Utils::countLessons() /home/agarzon/GIT/laracasts-downloader/App/Downloader.php:111
PHP   4. count() /home/agarzon/GIT/laracasts-downloader/App/Utils/Utils.php:51
> 0 new lessons and 0 episodes. 602ms elapsed with 6.00Mb of memory usage.


```

**Comment by carlosflorencio** [comment]
Hi,

I don't work with PHP for a long time and don't have an active account, would any of you mind to fix it and send a PR? I'd be much apreciated :).

Thanks

**Comment by carlosflorencio** [comment]
@cerberos @agarzon Can you guys test the PR from @storrella?

**Comment by agarzon** [comment]
I will do, but later today.

**Comment by cerberos** [comment]
It worked very well for me.

**Comment by agarzon** [comment]
Confirmed, it works. :)
