### ISSUE TITLE
Warning: Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by kossa** [carlosflorencio/laracasts-downloader#76]
Hello,

Anybody had this issue ?

![image](https://user-images.githubusercontent.com/1175584/48394790-2bcd3b80-e715-11e8-8763-7bad0d2864e7.png)

**Comment by carlosflorencio** [comment]
Hi,

Are you using the latest version with the new requirements in the readme? (algolia api keys)

**Comment by kossa** [comment]
Alright, thank you very much, works fine
