### ISSUE TITLE
update composer.lock to fix Guzzle Issue #2111

### ISSUE THREAD

**Issue by mouson** [carlosflorencio/laracasts-downloader#78]
use php 7.3 to start.php will show 

```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ......
```

guzzle package fix this problem in https://github.com/guzzle/guzzle/issues/2111 , please update composer.lock to apply this change

**Comment by carlosflorencio** [comment]
Hi,

Can you try this PR to see if it fixes the issue?
https://github.com/carlosflorencio/laracasts-downloader/pull/79

Would be good to confirm if it continues to work with older php versions (e.g 7.0,7.1,7.2) but don't have the time right now.
