### ISSUE TITLE
Incorrect episode name

### ISSUE THREAD

**Issue by ghost** [carlosflorencio/laracasts-downloader#8]
When grabbing an episode:
I get this in the console:

> Download started: 08 - Custom Components 101                                                                New . . . . Saving on series/learning-vue-step-by-step folder.

The file is then named: 
08-Custom Components 101                                                                New.mp4

Except that little problem, the downloader is working great with the new layout.
Thanks for your hard work.

**Comment by carlosflorencio** [comment]
Hi, fixed right now. Thanks!
