### ISSUE TITLE
Still working? Seems not...

### ISSUE THREAD

**Issue by Lambik** [carlosflorencio/laracasts-downloader#83]
Hi,

The tool doesn't seem to be working anymore for me. I still have an active subscription, but it hasn't downloaded any new courses since when I last started it about a month ago? But there are new lessons & series on the site, so...

**Comment by carlosflorencio** [comment]
I'm not maintaining the tool atm, but I accept pull requests 💪.

**Comment by Lambik** [comment]
Just to be sure it's not just on my end, could you verify that it's also not working for you? One never knows with software... I don't get any errors, but that doesn't necessarily mean anything.

**Comment by carlosflorencio** [comment]
I don't have an active subscription for years so I can't test.

**Comment by Lambik** [comment]
I'll close this as I'm sure it's a duplicate of #82
