### ISSUE TITLE
New series (full new series, not episodes to existing series) not detected

### ISSUE THREAD

**Issue by mattias** [carlosflorencio/laracasts-downloader#85]
It seems new series is also skipped in algolia now, it wasn't just the episode count that was wrong.
Example being https://laracasts.com/series/build-and-configure-a-staging-server

This specific serie doesn't even show up under the laracasts browse page if you try to search for it.

So it looks like the entire site needs to be scraped until (if) it's fixed.

**Comment by mattias** [comment]
I'm working on a fix which will only require a single page to be scraped, which will also optimize the episode count and remove all the scraping it currently does.

**Comment by carlosflorencio** [comment]
Hi @mattias.

Thanks for pointing this out and for your work on a fix.

:)

**Comment by carlosflorencio** [comment]
Fixed by https://github.com/carlosflorencio/laracasts-downloader/pull/86
