### ISSUE TITLE
algolia host unreachable

### ISSUE THREAD

**Issue by j3rrey** [carlosflorencio/laracasts-downloader#88]
Hey hey,

just wanted to download the new lessons for my next trip but the host seems to be unreachable I suspect Jeffrey changed something the Algolia calls don't show up in the network tab anymore.

```
====================================
Authenticating
====================================
> Successfull!

====================================
Starting Collecting the data
====================================
ERROR: Algolia error: Hosts unreachable: Resolving timed out after 1000 milliseconds,Resolving timed out after 1000 milliseconds,Resolving timed out after 3000 milliseconds,Resolving timed out after 3000 milliseconds%
```

**Comment by j3rrey** [comment]
Nevermind it was me using php 7.3... and i guess the continue statements in the switch argument

**Comment by carlosflorencio** [comment]
Hi, if this is no longer an issue can you close it?

**Comment by kossa** [comment]
@carlosflorencio,  I had the same error today 

![image](https://user-images.githubusercontent.com/1175584/77407471-77d2ca80-6db6-11ea-9c57-d4e1c0ae741c.png)

**Comment by carlosflorencio** [comment]
@kossa you'll have to debug it further I'm afraid.

**Comment by kossa** [comment]
I found the problem, I used PHP7.4.3, I changed it to 7.1 it works fine, may be I have to install a module for php7.4
