### ISSUE TITLE
when run php start.php, it shows curl error

### ISSUE THREAD

**Issue by SophieYe** [carlosflorencio/laracasts-downloader#89]
☁  laracasts-downloader  php start.php

====================================
Authenticating
====================================
ERROR: cURL error 6: Could not resolve: login (Domain name not found) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)%

Can you help me resolve this？

**Comment by carlosflorencio** [comment]
Can you debug it further? Checking the variables before making the curl request.

`Could not resolve: login` login is not a valid http address.

**Comment by SophieYe** [comment]
Very sorry, I cannot debug it further. I feel confused for this error. 
It's normal a year ago, but now it's wrong. 
My subscription will be expired on 14/08/2019, but now I don't know how to resolve this error, this make me sad. 

when I download use 

> php` start.php -s "envoyer" -s "envoyer"

it shows this error.

I download new version for laravel-downloader, but it shows same error.
I tried to delete vendor folder and composer install again , it also same error.

It don't show any other error, only this. 

Could you help me?
