### ISSUE TITLE
Use multiple connections

### ISSUE THREAD

**Issue by insign** [carlosflorencio/laracasts-downloader#9]
I think you could integrate this code https://github.com/ashbeats/PHP-Download-Accelerator

**Comment by carlosflorencio** [comment]
Hi,

Thanks for the suggestion, i have a super fast connection.
 If you test using that accelerator and proves to be much faster report it to me or send a pull request.

Thanks!

**Comment by ghost** [comment]
I think its not really important. In my Case im getting my full Download speed, so it doesnt matter.

**Comment by carlosflorencio** [comment]
I think that too. 

Will close it for now.
