### ISSUE TITLE
How exactly find algolia api key & id?

### ISSUE THREAD

**Issue by inDeev** [carlosflorencio/laracasts-downloader#92]
In network (dev tools) I'm only able to find this:
`o = "x-algolia-api-key" === r || "x-algolia-application-id" === r ? "hidden for security purposes" : e[r], t[r] = o`
I have subscription active.

**Comment by inDeev** [comment]
I've found it, it is about click on link in readme, not about search it directly on laracast...

**Comment by Dibbyo456** [comment]
I can't find it.. Can you help ? @inDeev
