### ISSUE TITLE
ERROR: The current node list is empty.

### ISSUE THREAD

**Issue by 4unkur** [carlosflorencio/laracasts-downloader#94]
![image](https://user-images.githubusercontent.com/7892851/66363302-a0513e80-e9a7-11e9-9cac-1a0d18bb5579.png)

I'm getting this error when I start downloading. I have updated the composer dependencies. Algolia details set in .env file
If it can be a problem I'm doing it inside an external HDD drive. It downloaded Laravel 6 from scratch series until 24th

**Comment by agarzon** [comment]
Having the same problem, just noticed today.

**Comment by carlosflorencio** [comment]
Is anyone available to send a PR to fix it?

Thanks

**Comment by Siddharaj6010** [comment]
@carlosflorencio I've submitted a PR that fixes this issue. Could you please have a look?

Also Thank you for building this great tool :)

**Comment by carlosflorencio** [comment]
@Siddharaj6010 🎖 thanks for your help, sorry for the delay.
