### ISSUE TITLE
ERROR: The current node list is empty

### ISSUE THREAD

**Issue by buddyy93** [carlosflorencio/laracasts-downloader#96]
[https://imgur.com/S5z6WHr](Error)

I keep getting this error, do you have any idea how to fix it ?

**Comment by carlosflorencio** [comment]
Hi,

Are you using the most up to date version?

This was recently fixed: https://github.com/carlosflorencio/laracasts-downloader/issues/94

**Comment by buddyy93** [comment]
Ah, yeah i just recloned the repo and now it works like a charm, thank you!

**Comment by kossa** [comment]
Facing the same error, I'm using PHP7.4 with latest version of laracasts-downloader

**Comment by erzgithub** [comment]
Yup same here, I recloned as well but still getting the same error. Can anyone share an answer to this really enjoyed this app for downloading laracasts series without having to click download at every page.

**Comment by mouson** [comment]
Laracasts refactor front end to  Inertia.js.  

https://laracasts.com/blog/the-best-of-both-worlds
