### ISSUE TITLE
429  Too Many Requests

### ISSUE THREAD

**Issue by thmsbgfrv** [carlosflorencio/laracasts-downloader#97]
When i try to download series it show me "[status code] 429 [reason phrase] Too Many Requests
" error. It only download 30 video,  now it is not working. Maybe jeffrey use throttle for that i dont know. But i try proxy and etc , they didnt work.  I  searched  bit on laracast but didnt found about download limits.

**Comment by kalsolio** [comment]
throttled by user_id

**Comment by lucassmacedo** [comment]
Same problem

**Comment by othyn** [comment]
If you check the response headers on https://laracasts.com/downloads/*, you get the following:

```
x-ratelimit-limit: 30
x-ratelimit-remaining: 0
x-ratelimit-reset: 1574425975
```

~~It appears a rate limit of 30 requests per 30 minutes/1 hour has been enforced (can't tell as I don't know my start time, will have to wait until my next window comes around).~~

~~Only way to fix this will be to read the headers from each response and sleep the script between downloads to space it out to 1 every minute OR just sleep the script until that timestamp is reached, resume, consume and sleep again.~~

**EDIT**:
Okay, misread the timestamp after beginning development on a PR for this. Its actually **30 requests per 24hrs**. Sorry guys!

This is going to be something where if the script reaches zero, you'll just have to wait until tomorrow. I can still build the header check in, but the wait time will be long!

**Comment by carlosflorencio** [comment]
If the @othyn response is right, this means there is a limit of 30 downloads per day.

The point should be to block scripts like this from working, possibilities:
- Ask Jeffrey to increase the download limit or provide some "official" app to download videos for later viewing.
- ~~Extend this tool to include a proxy usage to bypass the limit.~~ (creds based)

**Comment by othyn** [comment]
@carlosflorencio but, if @kalsolio is right, proxies won't work as the server is going to match it based on creds, not requesting IP/location.

I've whipped up a quick PR to check and handle the rate limit over my lunch break. Gonna submit it shortly.

**Comment by othyn** [comment]
#98 fixes this issue 👍

**Comment by othyn** [comment]
#99 Adds Docker compose support which, I hope, makes things better. With a few readme changes in there too to aid with setup instructions.

**Comment by thmsbgfrv** [comment]
@othyn Thanks for inform me :) And Sad for rate limits :(

**Comment by kalsolio** [comment]
after change a new account, you can download again.

**Comment by kalsolio** [comment]
en , can we merge m3u files to download videos?
